createsecret: true
resourcename: secret
namespace:
  - name: firstnamespace
  - name: secondnamespace
labels:
  name: demo-a
kind: Pod
podname: nginx-helmpod
containername: nginx-container
image: "nginx:1.16.0"
configname: nginx-configmap
volume:
  path: /usr/share/nginx/html
  pathname: nginx-path
  configname: nginx-configmap
type: Namespace
service:
  network:
    enabled: disable
  python:
    enabled: true
  nginxport:
    enabled: true
  type: NodePort
  labels:
    app: nginx
  port: 80
  protocol: TCP
  targetPort: 80
replicacount: 2
imagenginx: "nginx:1.16.0"
networkname: network
secretflag: createt456456
poddisruptionbudget:
  enabled: true
  minAvaliable: 1
  maxUnavailable: 1
extra:
  secret: []
secret:
  creds:
    secretid: "randomsecretid"
    secretidtwo: "randomesecrettwo"

secret1:
  secret2:
    secret3:
      blockkey:
        fromstring:
          active:
            secretName:
            key:

      haskey:
        fromstring:
          active:
        fromsecret:
            secretName:
            key:
